<a href="https://colab.research.google.com/github/christine127/Kaggle/blob/main/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')

In [ ]:
dataset =load_iris()

In [ ]:
df = pd.DataFrame(data = dataset.data, columns= dataset.feature_names)
df['target'] =dataset.target

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, roc_auc_score

## 모델 라이브러리
#분류
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
#KNN
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
rt = RandomForestClassifier()
dt = DecisionTreeClassifier()
lr = LogisticRegression()
xgb = XGBClassifier()
knn = KNeighborsClassifier()

models = [rt,dt,lr,xgb,knn]

In [ ]:
X = df.drop("target", axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, shuffle= True, 
                                                      random_state = 121)

In [ ]:
for model in models:
  model.fit(X_train, y_train)
  pred= model.predict(X_test)
  proba = model.predict_proba(X_test)
  print(model)
  accuracy = accuracy_score(y_test, pred)
  recall = recall_score(y_test, pred, average='macro')
  precision =  precision_score(y_test, pred, average= 'macro')
  f1 = f1_score(y_test, pred, average='macro')
  auc = roc_auc_score(y_test, proba, average='macro', multi_class= 'ovr')
  print("Accuracy:{:.6f} precision:{:.6f} recall:{:.6f} f1:{:.6f} auc:{:.6f}".format(accuracy, precision, recall, f1, auc))
  mtx = confusion_matrix(y_test, pred)
  print(mtx)


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
Accuracy:0.955556 precision:0.956944 recall:0.956944 f1:0.956944 auc:0.994893
[[14  0  0]
 [ 0 15  1]
 [ 0  1 14]]
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_le